// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package com.example.myimdb.grpc.recommendation;

public final class RecommendationProto {
  private RecommendationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecommendationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recommendation.RecommendationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code recommendation.RecommendationRequest}
   */
  public static final class RecommendationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recommendation.RecommendationRequest)
      RecommendationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendationRequest.newBuilder() to construct.
    private RecommendationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendationRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecommendationRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecommendationProto.internal_static_recommendation_RecommendationRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecommendationProto.internal_static_recommendation_RecommendationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecommendationRequest.class, Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecommendationRequest)) {
        return super.equals(obj);
      }
      RecommendationRequest other = (RecommendationRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecommendationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecommendationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecommendationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recommendation.RecommendationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recommendation.RecommendationRequest)
        RecommendationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecommendationProto.internal_static_recommendation_RecommendationRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecommendationProto.internal_static_recommendation_RecommendationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecommendationRequest.class, Builder.class);
      }

      // Construct using com.example.myimdb.grpc.recommendation.RecommendationProto.RecommendationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecommendationProto.internal_static_recommendation_RecommendationRequest_descriptor;
      }

      @Override
      public RecommendationRequest getDefaultInstanceForType() {
        return RecommendationRequest.getDefaultInstance();
      }

      @Override
      public RecommendationRequest build() {
        RecommendationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RecommendationRequest buildPartial() {
        RecommendationRequest result = new RecommendationRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecommendationRequest) {
          return mergeFrom((RecommendationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecommendationRequest other) {
        if (other == RecommendationRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt32();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recommendation.RecommendationRequest)
    }

    // @@protoc_insertion_point(class_scope:recommendation.RecommendationRequest)
    private static final RecommendationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecommendationRequest();
    }

    public static RecommendationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationRequest>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationRequest>() {
      @Override
      public RecommendationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecommendationRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RecommendationRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public RecommendationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecommendationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recommendation.RecommendationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @return A list containing the movieIds.
     */
    java.util.List<Integer> getMovieIdsList();
    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @return The count of movieIds.
     */
    int getMovieIdsCount();
    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The movieIds at the given index.
     */
    int getMovieIds(int index);
  }
  /**
   * Protobuf type {@code recommendation.RecommendationResponse}
   */
  public static final class RecommendationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recommendation.RecommendationResponse)
      RecommendationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendationResponse.newBuilder() to construct.
    private RecommendationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendationResponse() {
      movieIds_ = emptyIntList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecommendationResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecommendationProto.internal_static_recommendation_RecommendationResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecommendationProto.internal_static_recommendation_RecommendationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecommendationResponse.class, Builder.class);
    }

    public static final int MOVIE_IDS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList movieIds_;
    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @return A list containing the movieIds.
     */
    @Override
    public java.util.List<Integer>
        getMovieIdsList() {
      return movieIds_;
    }
    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @return The count of movieIds.
     */
    public int getMovieIdsCount() {
      return movieIds_.size();
    }
    /**
     * <code>repeated int32 movie_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The movieIds at the given index.
     */
    public int getMovieIds(int index) {
      return movieIds_.getInt(index);
    }
    private int movieIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getMovieIdsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(movieIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < movieIds_.size(); i++) {
        output.writeInt32NoTag(movieIds_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < movieIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(movieIds_.getInt(i));
        }
        size += dataSize;
        if (!getMovieIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        movieIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecommendationResponse)) {
        return super.equals(obj);
      }
      RecommendationResponse other = (RecommendationResponse) obj;

      if (!getMovieIdsList()
          .equals(other.getMovieIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieIdsCount() > 0) {
        hash = (37 * hash) + MOVIE_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getMovieIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecommendationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommendationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommendationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecommendationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecommendationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recommendation.RecommendationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recommendation.RecommendationResponse)
        RecommendationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecommendationProto.internal_static_recommendation_RecommendationResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecommendationProto.internal_static_recommendation_RecommendationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecommendationResponse.class, Builder.class);
      }

      // Construct using com.example.myimdb.grpc.recommendation.RecommendationProto.RecommendationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        movieIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecommendationProto.internal_static_recommendation_RecommendationResponse_descriptor;
      }

      @Override
      public RecommendationResponse getDefaultInstanceForType() {
        return RecommendationResponse.getDefaultInstance();
      }

      @Override
      public RecommendationResponse build() {
        RecommendationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RecommendationResponse buildPartial() {
        RecommendationResponse result = new RecommendationResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          movieIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movieIds_ = movieIds_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecommendationResponse) {
          return mergeFrom((RecommendationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecommendationResponse other) {
        if (other == RecommendationResponse.getDefaultInstance()) return this;
        if (!other.movieIds_.isEmpty()) {
          if (movieIds_.isEmpty()) {
            movieIds_ = other.movieIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMovieIdsIsMutable();
            movieIds_.addAll(other.movieIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureMovieIdsIsMutable();
                movieIds_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureMovieIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  movieIds_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList movieIds_ = emptyIntList();
      private void ensureMovieIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          movieIds_ = mutableCopy(movieIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @return A list containing the movieIds.
       */
      public java.util.List<Integer>
          getMovieIdsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(movieIds_) : movieIds_;
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @return The count of movieIds.
       */
      public int getMovieIdsCount() {
        return movieIds_.size();
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @param index The index of the element to return.
       * @return The movieIds at the given index.
       */
      public int getMovieIds(int index) {
        return movieIds_.getInt(index);
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @param index The index to set the value at.
       * @param value The movieIds to set.
       * @return This builder for chaining.
       */
      public Builder setMovieIds(
          int index, int value) {
        ensureMovieIdsIsMutable();
        movieIds_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @param value The movieIds to add.
       * @return This builder for chaining.
       */
      public Builder addMovieIds(int value) {
        ensureMovieIdsIsMutable();
        movieIds_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @param values The movieIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllMovieIds(
          Iterable<? extends Integer> values) {
        ensureMovieIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movieIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 movie_ids = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieIds() {
        movieIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recommendation.RecommendationResponse)
    }

    // @@protoc_insertion_point(class_scope:recommendation.RecommendationResponse)
    private static final RecommendationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecommendationResponse();
    }

    public static RecommendationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationResponse>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationResponse>() {
      @Override
      public RecommendationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecommendationResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RecommendationResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public RecommendationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommendation_RecommendationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommendation_RecommendationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommendation_RecommendationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommendation_RecommendationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024recommendation.proto\022\016recommendation\"(" +
      "\n\025RecommendationRequest\022\017\n\007user_id\030\001 \001(\005" +
      "\"+\n\026RecommendationResponse\022\021\n\tmovie_ids\030" +
      "\001 \003(\0052|\n\025RecommendationService\022c\n\022GetRec" +
      "ommendations\022%.recommendation.Recommenda" +
      "tionRequest\032&.recommendation.Recommendat" +
      "ionResponseB=\n&com.example.myimdb.grpc.r" +
      "ecommendationB\023RecommendationProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_recommendation_RecommendationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recommendation_RecommendationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommendation_RecommendationRequest_descriptor,
        new String[] { "UserId", });
    internal_static_recommendation_RecommendationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recommendation_RecommendationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommendation_RecommendationResponse_descriptor,
        new String[] { "MovieIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
