server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://59.110.49.185:3306/imdb
    username: dmsTest
    password: MyIMDBsx123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 59.110.49.185
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        myimdb: DEBUG
#    org:
#      springframework: DEBUG

