server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://59.110.49.185:3306/imdb
    username: dmsTest
    password: MyIMDBsx123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 59.110.49.185
#      database: 0

      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 5000ms
        shutdown-timeout: 100ms
        timeout: 5000ms


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
#      id-type: auto


# 日志写入文件
logging:
  file:
    path: /logs/imdb
    name: imdb.log
  level:
    root: info
    com:
      example:
        myimdb: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

